### ISSUE TITLE
Non block ads

### ISSUE THREAD

**Issue by alexsanfr** [AdguardTeam/ContentBlocker#103]
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:

http://prntscr.com/iag68c

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| (. 1.6.10)|
| Browser in use:| (Yandex Browser)|
| Filters enabled in Adguard:| (russian, Annoyances)|
| Device model:| (lg l90)|
| Operating system and version:| (e.g. Android 5.1.1)|
| Rooted or not? | (No) |

**Comment by ameshkov** [comment]
@alexsanfr добрый день! А это надо репортить вот сюда: http://agrd.io/report
