### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by azlie1992** [AdguardTeam/ContentBlocker#111]
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| (e.g. 1.6.10)|
| Browser in use:| (Samsung Interner/Yandex Browser)|
| Filters enabled in Adguard:| (e.g. English, Annoyances)|
| Device model:| (e.g. Google Pixel)|
| Operating system and version:| (e.g. Android 7.1.2)|
| Rooted or not? | (Yes/No) |

**Comment by vozersky** [comment]
@azlie1992 Hello! Looks like your report is empty, do you experience any problems with Content Blocker? Pls, let me know
