### ISSUE TITLE
[Question/FeatureRequest] 'style' rules

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/ContentBlocker#122]
Hi,
does ContentBlocker support 'style' rules?
I mean rules like that
`#$#item { ... }`

Otherwise, could you support them in the future?

Thanks anyway for your work :)

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| 2.1.2 |
| Browser in use:| Samsung Internet |
| Filters enabled in Adguard:| default + ITA |
| Device model:| M2 Note |
| Operating system and version:| Android 7.1.2 |
| Rooted or not? | No |

**Comment by ameshkov** [comment]
Unfortunately, it does not, and it seems browsers devs (both Yandex and Samsung) aren't really interested in improving the feature and adding more rules support :(

**Comment by superlex** [comment]
Ok, so it's due to browsers, not to ContentBlocker.
Thanks for the explanation.
