### ISSUE TITLE
Браузер Samsung Internet

### ISSUE THREAD

**Issue by a-ladanov** [AdguardTeam/ContentBlocker#124]
Я понимаю почему не блокируется Яндекс.Директ в Яндекс Браузере, но почему не блокируется в мобильном браузере Samsung Internet? Или должен блокироваться?

**Comment by ameshkov** [comment]
С яндексом проблемы вообще везде, не только в контент блокере. Они нынче шифруются высококлассно.

Контент блокером или например средствами iOS их вообще не победить.
