### ISSUE TITLE
User filter rules are being imported together with comments

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/ContentBlocker#126]
Hi,
when you import user filter rules comments are imported as well.
On the contrary, with AdguardBrowserExtension it doesn't occur:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/584

So I think it's a bug.

### Your environment
|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| 2.1.2 |
| Browser in use:| Samsung Internet |
| Filters enabled in Adguard:| default filter list |
| Device model:| M2 Note |
| Operating system and version:| Android 7.1.2 |
| Rooted or not? | No |

**Comment by ameshkov** [comment]
Tbh, I think this behavior needs to be changed in the browser extension. There's nothing bad about having comments in the user filter.

**Comment by superlex** [comment]
Ok :)

**Comment by superlex** [comment]
@ameshkov 
However, with AdguardBrowserExtension I noticed a strange behavior when you import a filter list that contains comments: at first they are not present, but if you close the browser and then open it and go to Adguard settings, they are there. Maybe it's an unwanted behavior. I tried with Firefox and Safari.
