### ISSUE TITLE
https://rgvqcsxqge.com/k3evz47w?key=7a4f1e968aa7846ef59a816bda8ffa09&psid=14231564

### ISSUE THREAD

**Issue by dbecht15** [AdguardTeam/ContentBlocker#132]
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| (e.g. 1.6.10)|
| Browser in use:| (Samsung Interner/Yandex Browser)|
| Filters enabled in Adguard:| (e.g. English, Annoyances)|
| Device model:| (e.g. Google Pixel)|
| Operating system and version:| (e.g. Android 7.1.2)|
| Rooted or not? | (Yes/No) |

**Comment by dbecht15** [comment]
Comes up everytime I open my screen or the internet

**Comment by vozersky** [comment]
Hi. It has nothing to do with Adguard. Looks like an adware page. As I can see it is blocked by Adguard Safebrowsing.
Start with reseting browser data and start page.
You should also want to check your device for adware/malware.
