### ISSUE TITLE
Error of the program

### ISSUE THREAD

**Issue by maria7628** [AdguardTeam/ContentBlocker#133]
the program does not correct with the publicity. Always Í have publicity in my information cor internet

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| (e.g. 1.6.10)|
| Browser in use:| (Samsung Interner/Yandex Browser)|
| Filters enabled in Adguard:| (e.g. English, Annoyances)|
| Device model:| (e.g. Google Pixel)|
| Operating system and version:| (e.g. Android 7.1.2)|
| Rooted or not? | (Yes/No) |

**Comment by maria7628** [comment]
Tengo publicidad en Internet. No desaparece. Indicar que debo hacer

**Comment by ameshkov** [comment]
Hello, you need to report it here:
https://agrd.io/report
