### ISSUE TITLE
Anti adblock killer - Reek Doesn't work!

### ISSUE THREAD

**Issue by Samucaaa** [AdguardTeam/ContentBlocker#136]
A lot of sites are using anti adblock (sites as www.revistagalileu.globo.com ) but the filter "anti adblock killer / Reek" doesnt't work it,  it's useless, don't destroy the anti adblockers. Please solve that

**Comment by ameshkov** [comment]
This filter is abandoned. You might want to use the "AdGuard Annoyances filter" instead, however it can't solve everything -- content blockers are quite limited to what the full AdGuard for Android version can do.
