### ISSUE TITLE
Unable to read full text on https://noticias.uol.com.br 

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/ContentBlocker#138]
### CustomerID:
1476762
### Steps to reproduce

1. Enable AdGuard Content blocker on YaBrowser
2. Go to (for example) https://noticias.uol.com.br 
3. Open any story, tap on "Read more"

### Expected behavior

It should open fine.

### Actual behavior

YaBrowser is "stuck"

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| (e.g. 1.6.10)| Latest version.
| Browser in use:| (Samsung Interner/Yandex Browser)| Latest YaBrowser
| Filters enabled in Adguard:| (e.g. English, Annoyances)|All Defaults
| Device model:| (e.g. Google Pixel)| Google Pixel
| Operating system and version:| (e.g. Android 7.1.2)| Android P
| Rooted or not? | (Yes/No) | No

**Comment by ameshkov** [comment]
Is it okay on Samsung?

**Comment by TheHasagi** [comment]
@ameshkov 
Yes, it's working fine, without any problems with Samsung Browser.

This weird issue happens only with a set of Content Blocker and YaBrowser.

**Comment by artemiv4nov** [comment]
Can't reproduce on latest version of Content Blocker. This problem may already be fixed
