### ISSUE TITLE
AdGuard isn't updating automatically

### ISSUE THREAD

**Issue by TGWGitHub** [AdguardTeam/ContentBlocker#147]
Starting with v2.2.3, the app is no longer updating its filters automatically despite that it says it's updating them properly in its main UI, but in the filter list all the filters are several days out of date.

This also was determined and verified by looking at the internet activity log for the app.

Manual update works fine however.

Tried reinstalling the app but to no avail.

The same issue is present on two different devices:

1. Nokia 3 running Android 8.0.0
2. Samsung A5 running Android 6.0.1

Last known good version was v2.2.2.

### Expected behavior
The filters should update automatically in the background.

### Actual behavior
The filters need to be updating manually. 

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| 2.2.3 |
| Browser in use:| Samsung Internet 7.4.00.70 |
| Filters enabled in Adguard:| English, Annoyances |
| Device model:| Samsung A5, Nokia 3 |
| Operating system and version:| 6.0.1, 8.0.0 |
| Rooted or not? | Not rooted |

**Comment by TGWGitHub** [comment]
Update 1: Currently I installed the older version (v2.2.2) to see if the issue will still persist, time will tell.

Is there a possibly that this might be an app-server-side issue and will affect all versions including the older versions pre v2.2.3 as well?

**Comment by ameshkov** [comment]
> Is there a possibly that this might be an app-server-side issue and will affect all versions including the older versions pre v2.2.3 as well? or the app is completely self-contained?

Most likely there's a bug, we didn't observe this issue on other AG products.

Waiting for @nkartyshov to investigate.

**Comment by nkartyshov** [comment]
Fixed.

**Comment by TGWGitHub** [comment]
OK great,  I uninstalled the older version, and installed the new (v2.2.4) after a phone reboot just to make sure the installation is as clean as possible.

Hope it works out, thanks!

**Comment by TGWGitHub** [comment]
Update: few minutes after installing v2.2.4 AdGuard is crashing constantly.

I took screenshots of 2 instances, (1) AdGuard crashed while I was using the broswer (Samsung Internet), and the second instance I was using another app (Calculator) with the broswer idling in the background.

Screenshots:

https://s8.postimg.cc/i6o1l8q51/Screenshot_2018-09-16-15-31-53-1.png
https://s8.postimg.cc/wd3sgh8px/Screenshot_2018-09-16-17-44-11-1.png

**Comment by TGWGitHub** [comment]
Update: AdGuard v2.2.4 crashes too often that I had to downgrade all the way to v2.1.2 to test if automatic updating works on that version.

**Comment by ameshkov** [comment]
> Update: AdGuard v2.2.4 crashes too often that I had to downgrade all the way to v2.1.2 to test if automatic updating works on that version.

Filed an issue:
https://github.com/AdguardTeam/ContentBlocker/issues/148

**Comment by TGWGitHub** [comment]
I'm monitoring issue (#148), but just wanted to let you know that the older v2.1.2 from (Feb 26) works flawlessly, updating in background seems to be working as expected.

**Comment by ameshkov** [comment]
@TGWGitHub please let us know if 2.2.5 helps, it is supposed to fix the issue

**Comment by TGWGitHub** [comment]
Alright, I just installed v2.2.5 and I'll report back my findings as soon as I verify it's working as expected or not
