### ISSUE TITLE
Use a placeholder for Christian era.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ContentBlocker#159]
http://adguard.oneskyapp.com/collaboration/translate/project/project/67053/language/2#/?keyword=%2321728362

Is it possible to use the placeholder?
© 2009-2018.
-> © 2009-%s.

Such like the placeholder in #48361665 of AG for Android.
© 2009–%s. AdGuard Software Ltd.

I hope it will automatically change its Christian era in AG for Android and AG content blocker.
Thanks.

**Comment by nkartyshov** [comment]
done
