### ISSUE TITLE
Why are Useful Ads filter and Safari filter enabled by default?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ContentBlocker#167]
Samsung Internet Browser and Yandex.Browser are Chromium-based browsers.

Why are Useful Ads filter and Safari filter enabled by default?

They should be disabled by default.
Please fix it.
Thanks.

**Comment by lancelot-moon** [comment]
Another question...
Why do you not enable Annoyance filter by default in all of your products?

**Comment by ameshkov** [comment]
Not everyone needs it. All kinds of online support chats for instance, some people use them.

**Comment by superlex** [comment]
@lancelot-moon 
As regards "Safari filter" enabled by default, you can read here:
https://github.com/AdguardTeam/ContentBlocker/issues/65
https://github.com/AdguardTeam/ContentBlocker/issues/77

**Comment by superlex** [comment]
So, "Safari" filter it isn't important for ContentBlocker?

**Comment by superlex** [comment]
> So, "Safari" filter it isn't important for ContentBlocker?

> The filter is now marked "obsolete", all the necessary rules are included into the base filter.

See https://github.com/AdguardTeam/ContentBlocker/issues/172

**Comment by ameshkov** [comment]
Necessary rules are now in the Base filter version, but they are present in iOS/CB/Safari versions of it.

**Comment by superlex** [comment]
Thank you for the clarification ;)
