### ISSUE TITLE
Does AG Content Blocker for Android not support JS rules?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ContentBlocker#171]
@AdamWr

1. Does AG Content Blocker for Android not support below JS rules?
```
example.com#%#AG_defineProperty('mars.video.triggerAdblockCBK', { get: function() { return function() {}; }, set: function() {} });
```

2. By Chrome with AG Browser Extension on PC, the above JS rules can work.
I don't know why it can't work in Samsung Internet Browser and Yandex.Browser with AG Content Blocker for Android since they're chromium-based browsers.

**Comment by superlex** [comment]
No it doesn't
https://github.com/AdguardTeam/ContentBlocker/issues/122
because of browser limitations.
You can use AdguardForAndroid
https://github.com/AdguardTeam/AdguardForAndroid
that works well with Samsung Internet too.

**Comment by lancelot-moon** [comment]
Thanks for your reply.
BTW, you're so interested in AG Content Blocker, compared with me.
I dislike Yandex.Browser.
How about suggesting Samsung Internet Browser to support Browser Extension, such like Firefox for Android?

**Comment by superlex** [comment]
> How about suggesting Samsung Internet Browser to support Browser Extension

It already supports browser extensions, ContentBlocker is a Samsung Internet extension (like AdGuardForiOS for Safari).
However, as @ameshkov said, 

> it seems browsers devs (both Yandex and Samsung) aren't really interested in improving the feature and adding more rules support :(

:(

**Comment by lancelot-moon** [comment]
Not at all.
Content Blocker isn't equal to Browser Extension.

**Comment by Alex-302** [comment]
CB does no support even CSS rules.

**Comment by ameshkov** [comment]
> it seems browsers devs (both Yandex and Samsung) aren't really interested in improving the feature and adding more rules support :(

And I would add Apple to this list as well :(
