### ISSUE TITLE
Please update a phrase's translation.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ContentBlocker#176]
@nkartyshov
@aalpatkina

http://adguard.oneskyapp.com/collaboration/translate/project/project/94269/language/2#/?keyword=%2329742831

`Ad blocker app to block ads in Yandex Browser and Samsung Internet browser only`

I ever notified Anna to together update the above phrase's translation when updating descriptions on google play.
Afterwards, descriptions on google play were updated, but nobody remembers the thing.
That phrase's translation is still old one.
Please update it because I think you'll release v2.3.5 soon.

Thanks.

**Comment by nkartyshov** [comment]
done
