### ISSUE TITLE
Why did you change the symbol "、" to "," in insert_filters_localization.sql?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ContentBlocker#177]
@nkartyshov 

https://github.com/AdguardTeam/ContentBlocker/commit/0023a6752f069fbe5253af2bc226eb8352d63235#diff-efba0bbedfe55cd7e1e061abe33d96f3

The localized symbol "、" is used in Taiwan, China and Japan...etc.
"、" and "," are different uses in our sentences.
I don't understand why to modify them in our translations.
May you recover the localized symbol "、"?

INSERT INTO filters_localization (filter_list_id, language_code, filter_name, filter_description) VALUES (10, 'zh-tw', '解除封鎖搜尋和自我推銷廣告之過濾器', '解除封鎖搜尋（Duckduckgo、Google、Bing、Yahoo）和自我推銷廣告之過濾器。自我推銷的定義：當一個於網站上的廣告恰好正在推銷這個網站或與其密切相關之其它的網站 / 社群媒體 / 等等時，這樣的廣告被認為是一種自我推銷的廣告。');

INSERT INTO filters_localization (filter_list_id, language_code, filter_name, filter_description) VALUES (14, 'zh-tw', 'AdGuard 惱人的事物過濾器', '封鎖於網頁上令人惱怒的元件，包含cookie通知、第三方的小工具和在頁的彈出式視窗。');

**Comment by nkartyshov** [comment]
@lancelot-moon This symbol "、" breaks the word wrap for Useful Ads description. https://github.com/AdguardTeam/ContentBlocker/issues/170#issuecomment-475172780

**Comment by lancelot-moon** [comment]
@ameshkov 

In AG for Android v3, this localized symbol "、" doesn't break the word wrap in filters' descriptions.
Filter unblocking search ads and self-promotion:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/nklC140.png)
</details><br/>

Annoyances filter:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/tVTtdBe.png)
</details><br/>

In AG content blocker v2.3.5, it also doesn't break the word wrap in Annoyances filter.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/MVuqU5h.png)
</details><br/>

The problem was only in Filter unblocking search ads and self-promotion.

Do you not find those symbols in Chinese interface are **different** between AG content blocker and AG for Android?

Please fix and recover them.
Thanks.

**Comment by lancelot-moon** [comment]
@ameshkov 

nkartyshov modified Chinese and Japanese localized symbol "、" in our translations.
https://github.com/AdguardTeam/ContentBlocker/commit/0023a6752f069fbe5253af2bc226eb8352d63235#diff-efba0bbedfe55cd7e1e061abe33d96f3

Will it affect in all your AG products?
Please don't do so!
It's Chinese and Japanese localized symbol...

**Comment by lancelot-moon** [comment]
For your reference:
https://en.wikipedia.org/wiki/Chinese_punctuation

**Enumeration comma ( 、 )**
The enumeration comma (U+3001 ideographic comma) or "dun comma" (Chinese: 頓號; pinyin: dùnhào; literally: 'pause mark') must be used instead of the regular comma when separating words constituting a list. Chinese language does not traditionally observe the English custom of a serial comma (the comma before and or or in a list), although the issue is of little consequence in Chinese at any rate, as the English "A, B, and C" is more likely to be rendered in Chinese as "A、B及C" or more often as "A、B、C", without any word for "and", see picture to the right.

From Wiki:
https://bit.ly/2HLWHdg

It seems that you wrongly used **Simplified Chinese (zh-CN) symbols in Traditional Chinese (zh-TW) interface**.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/idOzMha.png)
</details><br/>
