### ISSUE TITLE
Warn user if he tries to enable more than 8 filters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#18]
@vbagirov we need a text for that warning message.

We should warn user about following possible issues:
1. Greater chance of an incorrect blocking
2. Performance issues

**Comment by Revertron** [comment]
@vbagirov I'm waiting for texts :)

**Comment by Revertron** [comment]
Done with the coding, and took the texts from browser extension. Upped the limit to 10 filters.
