### ISSUE TITLE
May you release v2.3.7 to Google Play?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ContentBlocker#186]
It's v2.3.4 on Google Play.
1. May you release v2.3.7 to Google Play or wait for v2.4?
2. **Please update descriptions on Google Play.**
I added a link.
Thanks.

**Comment by lancelot-moon** [comment]
Google Play doesn't allow your partner's store link on Google Play.
I cancel this.

**Comment by superlex** [comment]
@lancelot-moon 
Could you explain better

> Google Play doesn't allow your partner's store link on Google Play.

, please?
Currently you can receive v2.3.7 by enjoying beta program (on Google Play).
