### ISSUE TITLE
не блокирует мошенников в Яндекс. Браузер на Андроид

### ISSUE THREAD

**Issue by alfacs** [AdguardTeam/ContentBlocker#187]
не блокирует мошенников в Яндекс. Браузер на Андроид
[ссылка](https://www.comss.ru/page.php?id=6146) 
скриншот:
![S90725-133100](https://user-images.githubusercontent.com/13941510/61867801-aa06f200-aee0-11e9-8e1a-5f44478dc6ac.jpg)

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| (e.g. 1.6.10)|
| Browser in use:| (Samsung Interner/Yandex Browser)|
| Filters enabled in Adguard:| (e.g. English, Annoyances)|
| Device model:| (e.g. Google Pixel)|
| Operating system and version:| (e.g. Android 7.1.2)|
| Rooted or not? | (Yes/No) |

**Comment by Alex-302** [comment]
@alfacs в настройках браузера контент-блокер включен? Какие фильтры включены?

**Comment by alfacs** [comment]
да.
Причем и встроенный от Яндекс. Браузер, и Adguard. Версия браузера: бета, 19.6.4 от 17 июля, сборка 345

**Comment by Alex-302** [comment]
А можете в аналогичном браузере с контент блокером проверить?
https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser&hl=ru
Может версия браузера с глюком каким-то.

**Comment by artemiv4nov** [comment]
На данный момент реклама в браузере вырезается, задача закрыта.
