### ISSUE TITLE
Cannot import user filter by URL

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ContentBlocker#191]
### Prerequisites

Cannot import filter by URL from PC.
URL `http://192.168.88.100:88/1.txt`
File is located on [HFS](https://www.rejetto.com/hfs/) server.
This URL can be opened in browser and imported in AdGuard for Android.

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 2.4.0
- **Browser:** Samsung Internet
- **Device model:** Sony Xperiz XZ1 compact
- **Operating system and version:** Android 9

### Expected Behavior

User filter imported;

### Actual Behavior

User filter not imported;

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/65140136-95ddfd80-da16-11e9-9689-738e3fd14e4d.png)

</details>

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
`To reproduce this issue:`
-Get Android 9+ device
-Try to import filter with `http` protocol

- Reinstall AG
- Try to reproduce
