### ISSUE TITLE
Copy/paste buttons are not visible

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ContentBlocker#192]
Copy/paste buttons are not visible in text fields. No reaction on long tap and multiple.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 2.4.0
- **Browser:** Samsung Internet
- **Device model:** Sony Xperiz XZ1 compact
- **Operating system and version:** Android 9

### Expected Behavior

Buttons are displayed.

### Actual Behavior

No buttons.

**Comment by admitrevskiy** [comment]
Done.
