### ISSUE TITLE
CB does not block some ads in Samsung Internet

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ContentBlocker#196]
Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/41711

URL: https://forums.hardwarezone.com.sg

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Some requests are not blocked, even Google ads.

- **AdGuard version:** v2.5.3
- **Browser:** Samsung Internet 10.1.00.27
- **Device model:** Xperia XZ1 compact
- **Operating system and version:** Android 9
- Filters: Base, Tracking protection, Social, Annoyances, Russian

### Expected Behavior

Ads are blocked.

### Actual Behavior

Ads are not blocked.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/66222953-fd64a000-e6da-11e9-8472-5091e1c68b79.png)

</details>

### Additional Information

HAR file from Samsung Internet:

[forums.hardwarezone.com.sg.har.txt](https://github.com/AdguardTeam/ContentBlocker/files/3691383/forums.hardwarezone.com.sg.har.txt)

<details>

<summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/66223294-ca6edc00-e6db-11e9-8486-010d875a5424.png)

</details>

As you can see, there are a lot of requests, which must be blocked.

**Comment by Alex-302** [comment]
UPD: not reproduced in Yandex Browser.

**Comment by Luniz62** [comment]
Same here. I use Samsung Internet 10.1.00.27 and AdGuard ContentBlocker 2.5.3. I also tried Adguard 2.5.2 and 2.3.7, but no changes.

There are no issues with Samsung Internet 9.4.00.45.

**Comment by ameshkov** [comment]
@Luniz62 we'll look into it asap, thank you!

**Comment by artemiv4nov** [comment]
@Luniz62 we fixed Base Filter for this site, re-check, please.
