### ISSUE TITLE
Ресурсы mail.ru

### ISSUE THREAD

**Issue by Hawkrus** [AdguardTeam/ContentBlocker#20]
Все ресурсы mail.ru некорректно отображаются:
https://auto.mail.ru/
https://horo.mail.ru/
https://realty.mail.ru/
https://health.mail.ru/
https://afisha.mail.ru/
https://cloud.mail.ru/
https://otvet.mail.ru/
https://pogoda.mail.ru/
https://sport.mail.ru/
https://tv.mail.ru/
http://torg.mail.ru/
https://cars.mail.ru/
![screenshot 20 2016 9-59](https://cloud.githubusercontent.com/assets/19652388/16185652/1f94181a-36ce-11e6-972e-161eb34436d5.PNG)

**Comment by Alex-302** [comment]
Не повторяется. Какие фильтры?

**Comment by Hawkrus** [comment]
![tempfileforshare_2016-06-20-11-49-24](https://cloud.githubusercontent.com/assets/19652388/16188246/3a1482e2-36dd-11e6-8d64-ba9de644e0ec.jpg)

**Comment by Alex-302** [comment]
выключайте по одному и проверяйте

**Comment by Hawkrus** [comment]
Русский фильтр, что логично...

**Comment by Alex-302** [comment]
логики никакой, ломатть может любой фильтр, в котором есть общие правила.
Проверьте по очереди
```
@@||auto.mail.ru^$jsinject
@@||auto.mail.ru^$urlblock
```

**Comment by Hawkrus** [comment]
Добавил в пользовательский фильтр по очереди, ничего не изменилось ни для полной версии сайта, ни для мобильной:
![tempfileforshare_2016-06-20-13-03-53](https://cloud.githubusercontent.com/assets/19652388/16190658/11234ed4-36e9-11e6-9202-cb7e56706622.jpg)
![tempfileforshare_2016-06-20-13-05-13](https://cloud.githubusercontent.com/assets/19652388/16190669/22701ae6-36e9-11e6-9306-0ea2ca539d9e.jpg)
![tempfileforshare_2016-06-20-13-05-54](https://cloud.githubusercontent.com/assets/19652388/16190696/4438103e-36e9-11e6-9de9-5d1606099bc9.jpg)
