### ISSUE TITLE
Реклама отображается в яндексе андроид

### ISSUE THREAD

**Issue by maxpetrgit** [AdguardTeam/ContentBlocker#203]
Шо за херня. После апдейта отображается гугл адс на всех сайтах. Адгуард в настройках браузера яндекс андроид включен

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| (e.g. 1.6.10)|
| Browser in use:| (Samsung Interner/Yandex Browser)|
| Filters enabled in Adguard:| (e.g. English, Annoyances)|
| Device model:| (e.g. Google Pixel)|
| Operating system and version:| (e.g. Android 7.1.2)|
| Rooted or not? | (Yes/No) |

**Comment by TheHasagi** [comment]
@maxpetrgit 

А можно конкретнее, где именно отображается реклама, обновлены ли фильтры и желательно скриншот.

**Comment by maxpetrgit** [comment]
Скриншот во вложении, Adguard включен, фильтры актуализированы
Реклама на всех сайтах, не только на mail.ru

Am 15. November 2019 08:08:11 schrieb Alexander <notifications@github.com>:

**Comment by ameshkov** [comment]
Из почты сюда скриншоты не подтягиваются к сожалению.

А у вас релизный яндекс браузер или бета/альфа?

**Comment by maxpetrgit** [comment]
Версия 19.10.1, build 81.
Adguard переустановил, реклама всё равно присутствует. У меня единичный 
случай или проблема есть в данный момент у многих пользователей?

Am 15. November 2019 11:36:29 schrieb Andrey Meshkov 
<notifications@github.com>:

**Comment by artemiv4nov** [comment]
Подтверждаю, что Яндекс.Браузер не использует блокировщики рекламы (в нашем случае, AdGuard Content Blocker) для фильтрации трафика с HTTP сайтов.

Версия ЯБ: 19.9.6 release Build 88
Как воспроизвести:
1) Скачиваем ЯБ необходимой версии и последнюю версию Content Blocker из Play Store
2) Первично настраиваем Content blocker и устанавливаем в настройках ЯБ блокировщиком рекламы Content Blocker
3) Заходим на сайт example.org (HTTP соединение)
4) Видим, что весь сайт загружается, как надо
5) Переходим в Content Blocker в раздел "User filter"; добавляем правило `example.org##body`
6) Переходим в ЯБ, обновляем example.org и видим, что сайт полностью отображается, как обычно (Баг яндекса: тело сайта не должно быть отображено)

7) Переходим на lenta.ru (HTTPs соединение)
8) Видим, что сайт загрузился
9) Переходим в Content Blocker в раздел "User filter"; добавляем правило `lenta.ru##body`
10) Переходим в ЯБ, обновляем lenta.ru и видим, что сайт не загрузился – белое окно (пользовательский фильтр применился, всё верно)

**Comment by ameshkov** [comment]
В Яндекс мы уже об этом написали, теперь дело за ними.

@artemiv4nov давай на следующей неделе перепроверим пофиксили ли это в альфа версии ЯБраузера хотя бы

**Comment by maxpetrgit** [comment]
У меня реклама и на https сайтах
![Screenshot_20191122-081846](https://user-images.githubusercontent.com/47632696/69405935-3693b680-0d01-11ea-9ffc-4b09a4ce369c.png)

**Comment by ameshkov** [comment]
@maxpetrgit у них в версии 19.10.* вообще полностью сломана блокировка. В версии 19.8 -- сломана частично.

К вам видимо попал билд 19.10 потому что они постепенно его выкатывают.

В общем и целом надо просто ждать пока это исправят. Яндекс о проблеме знает, но если вы им напишете - это лишним не будет.

**Comment by artemiv4nov** [comment]
Протестировал ещё раз:
на версии `YB 19.10.2 released Nov 25, 2019, Build 116` фильтрация по-прежнему поломана;
на версии `YB Beta 19.10.4 released Dec 6, 2019, Build 181` фильтрация работает на HTTP и HTTPs.

**Comment by maxpetrgit** [comment]
У меня 19.10.3 - это скорее всего второй апдейт после проблемы. Всё ок. 
Пропускается только на определённых сайтах, скорее всего, партнёрская 
реклама. Партнёры это яндекса или эдгуарда - хз . Гугл адс - нет.

Am 7. Dezember 2019 10:06:13 schrieb Artem Ivanov <notifications@github.com>:

**Comment by Alex-302** [comment]
> Партнёры это яндекса или эдгуарда - хз

мы никогда не разблокируем рекламу. Рекламный Яндекс браузер это сам делает - разблокирует яндекс директ, в случае использования контент блокера. С полноценным Адгардом для Android они такое сделать не могут.

**Comment by maxpetrgit** [comment]
У меня на mail.ru такая реклама проскакивает
![Screenshot_20191209-150857](https://user-images.githubusercontent.com/47632696/70442310-5e6f7200-1a96-11ea-9344-74e8a5c2fbf5.png)

**Comment by Alex-302** [comment]
@maxpetrgit mail.ru просто обходит блокировщики. Только полноценному Адгарду для Android она под силу

**Comment by maxpetrgit** [comment]
Спасибо за подсказку! Стоял Adquard из Play Store. Поставил apk с сайта. Рекламы нет.

**Comment by Alex-302** [comment]
Да, не все знают про Адгард для Android. Напрямую об этом заявить в приложении нельзя из-за политики Гугла, но можно если зайти на сайт и скачать необходимый продукт.
