### ISSUE TITLE
"Do not block useful ads" option is constantly re-enabled

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/ContentBlocker#205]
### Issue Details

- **AdGuard version:**
  - 2.5.5
- **Browser:**
  - Samsung Internet
- **Device model:**
  - Unspecified
- **Operating system and version:**
  - Unspecified

### Expected Behavior

Turning off "Do not block useful ads" should disable that option for good.

### Actual Behavior

"Do not block useful ads" option re-enables upon each filter update.

### Screenshots

N/A

### Additional Information

Submitted by user 2393578

**Comment by ameshkov** [comment]
Why is it enabled in the first place? It is supposed to be disabled by default

**Comment by admitrevskiy** [comment]
Done.
