### ISSUE TITLE
Some element hiding rules are not applied

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ContentBlocker#208]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Open https://overclockers.ru/blog/TopDeals/show/31961/flagmanskie-smartfony-s-podderzhkoj-5g-na-aliexpress-po-cene-ot-20-700-rublej and scroll down to comments

- **AdGuard version:**
  -  2.5.5
- **Browser:** Samsung Internet
  - 
- **Device model:**
  - 
- **Operating system and version:** Android 9
  - 

### Expected Behavior

Elements are hidden.

### Actual Behavior

Elements are not hidden.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/69579488-4221fe80-0fdb-11ea-84a0-7a1471e17e81.png)

</details>

### Additional Information

Enabled Base, Social and Russian filters.
These rules must hide that elements:
```
~vk.com,~vkontakte.ru##a[href^="http://vkontakte.ru/share.php"]
~twitter.com##a[href^="http://twitter.com/home?"]
~facebook.com##a[href^="http://www.facebook.com/sharer.php?"]
~plus.google.com##a[href^="https://plus.google.com/share"]
```
They are exist in optimized version of Social filter:
https://filters.adtidy.org/extension/android-content-blocker/filters/4_optimized.txt

**Comment by Alex-302** [comment]
Strange. Not reproduced at the moment(Samsung Browser)

**Comment by admitrevskiy** [comment]
Testing instructions for QA:

- Please, recheck this issue
