### ISSUE TITLE
mail.ru is broken in Samsung Internet

### ISSUE THREAD

**Issue by Hawkrus** [AdguardTeam/ContentBlocker#21]
Продолжение закрытой темы:

> Все ресурсы mail.ru некорректно отображаются:
> https://auto.mail.ru/
> https://horo.mail.ru/
> https://realty.mail.ru/
> https://health.mail.ru/
> https://afisha.mail.ru/
> https://cloud.mail.ru/
> https://otvet.mail.ru/
> https://pogoda.mail.ru/
> https://sport.mail.ru/
> https://tv.mail.ru/
> http://torg.mail.ru/
> https://cars.mail.ru/

Добавил в пользовательский фильтр по очереди, ничего не изменилось ни для полной версии сайта, ни для мобильной:
![tempfileforshare_2016-06-20-13-03-53](https://cloud.githubusercontent.com/assets/19652388/16190866/1bdb84da-36ea-11e6-938e-53ffe4981f1a.jpg)
![tempfileforshare_2016-06-20-13-05-13](https://cloud.githubusercontent.com/assets/19652388/16190869/2169b520-36ea-11e6-87d8-91469d5bc9e1.jpg)
![tempfileforshare_2016-06-20-13-05-54](https://cloud.githubusercontent.com/assets/19652388/16190876/27e2c4d2-36ea-11e6-9f4c-4b050da176c2.jpg)

**Comment by ameshkov** [comment]
А какие фильтры включены?

**Comment by Alex-302** [comment]
здесь скрин с фильтрами
https://github.com/AdguardTeam/ContentBlocker/issues/20#issuecomment-227085911

**Comment by ameshkov** [comment]
@Alex-302 через chrome://inspect посмотри что лишнее заблокировалось

**Comment by Alex-302** [comment]
у меня же не повторилось. Давал на проверку исключения
```
@@||auto.mail.ru^$jsinject
@@||auto.mail.ru^$urlblock
```
но не помогли

**Comment by ameshkov** [comment]
@Hawkrus а какая точно версия яндекс браузера?

**Comment by Hawkrus** [comment]
Samsung Intenet 4.0.20-6

**Comment by ameshkov** [comment]
Ага, понятно, хз почему подумал на ябраузер:)

**Comment by Revertron** [comment]
А скрин-то не с контент-блокера, а из полной версии Адгарда. Мы точно тут контент-блокер обсуждаем?

**Comment by Alex-302** [comment]
@Revertron 
а можешь с русским фильтром на самсунге проверить в том браузере?

**Comment by ameshkov** [comment]
Ойвэй, и дейтсивтельно. Давайте закрою тут задачу.

**Comment by Revertron** [comment]
Протестил несколько сайтов из списка. Всё отлично загружается и ничего не обезображивается. Не понимаю что там еще можно искать.

**Comment by ameshkov** [comment]
@Revertron на "большой" версии? А проверь с контент блокером на всякий случай

**Comment by Revertron** [comment]
Проверил, всё отлично работает.

**Comment by Hawkrus** [comment]
> всё отлично работает

А какой браузер, какая версия?

**Comment by Hawkrus** [comment]
У меня Note 4, версия Samsung Intenet 4.0.20-6
С русским фильтром портит страницы, как на скриншотах.

**Comment by Revertron** [comment]
Что ж, ставьте Яндекс браузер. Бету пока что.

**Comment by Hawkrus** [comment]
А для Samsung Internet будет дорабатываться?

**Comment by Revertron** [comment]
Пока что мне кажется, что Самсунг должен дорабатывать свой браузер.

**Comment by ameshkov** [comment]
А мне вот так не кажется. Очевидно надо найти проблему

**Comment by ameshkov** [comment]
Вопрос только один: проблема с андроид-версией Adguard ИЛИ с Adguard Content Blocker?

**Comment by ameshkov** [comment]
А, все, вижу, с content blocker.

**Comment by ameshkov** [comment]
@Hawkrus Adguard это единственный content blocker который используется?

**Comment by Revertron** [comment]
@Hawkrus А Adguard при этом включен, или выключен?

**Comment by Revertron** [comment]
На S7 mail.ru тоже ругается, но только когда перехожу на полную версию. А так, загружаются мобильные страницы по умолчанию. Но и полные совершенно нормально отображаются, сразу проверил и то и то.

**Comment by Hawkrus** [comment]
@Revertron у меня по факту свежее версия Samsung Internet, она пришла с апдейтом системы, таким образом у вас тоже перестанут работать ресурсы mail.ru, когда обновится браузер.

**Comment by ameshkov** [comment]
@Revertron давай поищем какую-нибудь бета-программу у самсунга что-ли.

**Comment by Hawkrus** [comment]
[Здесь](http://4pda.ru/forum/index.php?showtopic=726314) есть установочные apk.

**Comment by vgavrish** [comment]
id 1430679
Браузер Samsung 4.2.00.93
при установке галочки на "Русский фильтр" возникает проблема  на touch.otvet.mail.ru (идет 
бесконечная загрузка)
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19417284/e43487be-93b1-11e6-82fc-ec4e9d07f875.png)

**Comment by ameshkov** [comment]
@gshumihin
