### ISSUE TITLE
Ресурсы mail.ru (3)

### ISSUE THREAD

**Issue by Hawkrus** [AdguardTeam/ContentBlocker#22]
> Все ресурсы mail.ru некорректно отображаются:
> https://auto.mail.ru/
> https://horo.mail.ru/
> https://realty.mail.ru/
> https://health.mail.ru/
> https://afisha.mail.ru/
> https://cloud.mail.ru/
> https://otvet.mail.ru/
> https://pogoda.mail.ru/
> https://sport.mail.ru/
> https://tv.mail.ru/
> http://torg.mail.ru/
> https://cars.mail.ru/
> 
> А скрин-то не с контент-блокера, а из полной версии Адгарда. Мы точно тут контент-блокер обсуждаем?

Фильтры указаны с ContentBlocker, исключения фильтрации были наложены на обычный Adguard, потому что в ContentBlocker не нашёл возможности указать ручные фильтры и предположил, что приложения используют общие ресурсы. По факту проблема не решена, с включённым русским фильтром сайты mail.ru уродуются.

**Comment by ameshkov** [comment]
Duplicate for #21
