### ISSUE TITLE
Adguard isn't blocking Cookie/General Popups

### ISSUE THREAD

**Issue by EktoHunter** [AdguardTeam/ContentBlocker#244]
### Prerequisites

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed (I didn't see anything like this)

### Issue Details

- **AdGuard version:**
  - 3.5.31
- **Browser:**
  - Edge Chromium, Windows (Extension) and Android (Adguard for Android on Android, Lifetie license)
- **Device model:**
  - Windows 10 Laptop, Huawei P30 Pro
- **Operating system and version:**
  - Windows 10 20H2, Android 10

### Expected Behavior

I have the "Fanboy's Annoyances" and "IDC About Cookies" filters enabled, so I would expect to not get Cookie-Popups. However, over the past few days, Cookie-Popups on almost no website has been removed, both on Android and Windows.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/23218251/105087825-61130800-5a9b-11eb-9707-469e245e5b65.png)

</details>

### Additional Information

I have reinstalled Adguard, disabled and enabled the filters again, added more filters. Idk why this is happening.

**Comment by ameshkov** [comment]
Please report the website that's doing it to https://agrd.io/report, this may be a filters issue and filters devs need to know more about the website where it happens to fix this in AdGuard Annoyances filter (we recommend it over others).

**Comment by EktoHunter** [comment]
This doesnt only happen on a single site, I`ve been experiencing this on almost all websites. Youtube, Reddit, WSJ, Reuters, NYT etc. That's why I posted it in here. I have the AdGuard Annoyances filter enabled aswell.
![image](https://user-images.githubusercontent.com/23218251/105089927-0b8c2a80-5a9e-11eb-96fd-39fe834e0008.png)
![image](https://user-images.githubusercontent.com/23218251/105090010-29598f80-5a9e-11eb-8213-d88bb431ae6f.png)
![image](https://user-images.githubusercontent.com/23218251/105090049-35dde800-5a9e-11eb-9c12-d580e425b352.png)

**Comment by ameshkov** [comment]
Try disabling IDC just in case, does it change anything?

**Comment by EktoHunter** [comment]
> Try disabling IDC just in case, does it change anything?

No, it didn't change anything
