### ISSUE TITLE
Microsoft Edge browser and Vivaldi browser synchronization cannot be used when AdGuard is activated

### ISSUE THREAD

**Issue by sH1222J** [AdguardTeam/ContentBlocker#247]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 3.6
  - 
- **Browser:** Microsoft Edge , Vivaldi browser 
  - 
- **Device model:** Galaxy s10e
  - 
- **Operating system and version:** Android 10
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Microsoft Edge browser and Vivaldi browser synchronization cannot be used when AdGuard is activated
Disabling AdGuard will enable your browser's sync feature.
I want to use AdGuard and Micro Edge browser at the same time.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #3728](https://github.com/AdguardTeam/AdguardForAndroid/issues/3728) via [**ZenHub**](https://www.zenhub.com/)
