### ISSUE TITLE
Incorrect site rendering

### ISSUE THREAD

**Issue by Truman82** [AdguardTeam/ContentBlocker#249]
### Steps to reproduce

1. Go to www.9to5google.com with your adblocker activated on samsung browser. There should be three dots in middle upper side of screen which folöows you when you scroll down or up the website.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| (e.g. 1.6.10)|
| Browser in use:| (Samsung Interner/Yandex Browser)|
| Filters enabled in Adguard:| (e.g. English, Annoyances)|
| Device model:| (e.g. Google Pixel)|
| Operating system and version:| (e.g. Android 7.1.2)|
| Rooted or not? | (Yes/No) |

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardFilters #78132](https://github.com/AdguardTeam/AdguardFilters/issues/78132) via [**ZenHub**](https://www.zenhub.com/)
