### ISSUE TITLE
Feature Request - Remove Blanked Space

### ISSUE THREAD

**Issue by hitechlover** [AdguardTeam/ContentBlocker#255]
Dear Developer, 

We found Adguard failed to remove the blank spaces where ads are blocked on many websites. Please implement codes in Adguard that are smart enough to detect blank space and remove them, to make web pages look better without the huge gaps in between web contents.

A good example of the blank space issue is from this site and many others:
https://www.tomsguide.com/amp/news/samsungs-new-galaxy-books-are-poised-to-shake-up-laptops-including-macbooks

There are millions of websites and if you keep adding them to the filter lists, they will keep getting larger which makes things lower over time. Loading will suffers due to massive filters. The solution is to injects code into Adguard to remove blank spaces for this purpose. 

Thank You

**Comment by Chinaski1** [comment]
Hello @hitechlover 

As a rule, we hide blocked elements with cosmetic filters.
If you notice any empty space remaining on any site, it is advisable to send a complaint to the filter developers.

How to make a report:
- Open AdGuard CB app -> Support -> Missed ads -> Fill the form and send the report
- From the direct link: agrd.io/report (All information will need to be filled in manually)

After submitting a complaint, the filter developers will hide blanked space shortly.
