### ISSUE TITLE
Проблема с youtube.com в Samsung Internet

### ISSUE THREAD

**Issue by a-zagvazdin** [AdguardTeam/ContentBlocker#257]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 2.6.2
- **Browser:**
  - Samsung Internet 14.0.3.5/5500
- **Device model:**
  - Samsung J3 (2017)
- **Operating system and version:**
  - Android 9

### Expected Behavior
Блокировка рекламы и воспроизведение ролика

### Actual Behavior
Черный экран 

</details>

### Additional Information
При использовании m.youtube.com через Samsung Internet вместо ролика черный экран около 20 секунд.
При отключении расширения Adguard все нормально, но появляется реклама.
Я попробовал удалить кэш и переустановить расширение, но не помогает.
Установлены фильтры: Базовый, Русский, Мобильный, Раздражители
Проблема появилась около 2-3 недель назад, возможно из-за обновления браузера, так как в changelog есть упоминание блокировщиков.

**Comment by Alex-302** [comment]
@a-zagvazdin Hi. Content Blocker for Samsung Internet cannot apply advanced rules(browser's content blocker API does not support them). Only AdGuard for Android can block them.

**Comment by Sergey-Lyapin** [comment]
https://adguard.com/en/adguard-android/overview.html
