### ISSUE TITLE
Cancel subscription and refund

### ISSUE THREAD

**Issue by Johnmurphystory** [AdguardTeam/ContentBlocker#258]
I just saw that this Adguard subscription only works on Yandex and Samsung browsers and I never use either of those browsers, so after paying for a year without realizing that fact I need to cancel my subscription ASAP and refund the most recent amount I was charged of $31.55.  Unfortunately, this product does not help me at all. The Receipt # 15259127-11133561 is what I received in my email. The charge has not been withdrawn from my account yet, so maybe it can be canceled before that happens.
Thanks, 
John Story

**Comment by ameshkov** [comment]
Hello, you need to contact our support at support@adguard.com

Also, AdGuard android app is capable of much more, but it's not available on Play store, you can get it from the website: https://adguard.com/

Please give it a try first.
