### ISSUE TITLE
Not working when installed via F-droid

### ISSUE THREAD

**Issue by Offerel** [AdguardTeam/ContentBlocker#262]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v2.6.2
- **Browser:**
  - Samsung Internet
- **Device model:**
  - Galaxy S9
- **Operating system and version:**
  - Android 11

### Expected Behavior

- open F-droid store
- install AdGuard
- open AdGuard
- activate it in Samsung Internet

### Actual Behavior

- open F-droid store
- install AdGuard
- open AdGuard
- activate it in Samsung Internet
- not available as AddOn in Samsung Internet

**Comment by ameshkov** [comment]
Samsung checks the application signature. F-Droid version is signed by F-Droid and Samsung does not have it in the list of trusted signatures.

**Comment by Offerel** [comment]
Is there some small chance to include the F-droid signature in a future release?

**Comment by ameshkov** [comment]
Depends on Samsung, not on us

**Comment by Offerel** [comment]
Ahhh sorry, sure,  have misinterpreted this. I have no idea how to reach this out to Samsung. If you have a contact, it would be nice if you could ask them.

BTW: i have tried to develop an AddOn for Samsung Internet, but I failed. It works currently for Firefox, Chromium on Desktop and in Fennec and Kiwi on Android for syncing bookmarks. If you have an idea where to place this for Samsung Internet, I would be really happy.

**Comment by ameshkov** [comment]
I reckon you made a WebExtensions add-on? Tbh, I don't think Samsung supports this kind of add-ons.

**Comment by Offerel** [comment]
Yes, it's a WebExtension. It uses the bookmark api primary, but also some other api's for messaging, notifications and basic tab functions (without the api). As a backend you can use a simple WebDAV share for a real basic functionality or a PHP/SQLite/MySQL backend (available as a free separate repositorie at my GitHub). Purpose is it to sync bookmarks without any Third-party server, so you can have all in your own control.

Sure, it's not so fancy as Firefox Sync or Chrome, but it works at least for my use case's . And more important, it works browser independent and between different browsers.
