### ISSUE TITLE
Kasar ani yasar ben final deyim

### ISSUE THREAD

**Issue by Oksaniffet** [AdguardTeam/ContentBlocker#271]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Browser:**
  - 
- **Device model:**
  - 
- **Operating system and version:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Chinaski1** [comment]
You have created an empty task.
If you encounter issues while using the application, please contact support team at support@adguard.com
