### ISSUE TITLE
Confusing ,i want content blocker,not GITHUB,I AM 70,HARDLY STUDENT,I WILL RATE WHEN APP ACTUALLY WORKS

### ISSUE THREAD

**Issue by psgomez** [AdguardTeam/ContentBlocker#272]
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| (e.g. 1.6.10)|
| Browser in use:| (Samsung Interner/Yandex Browser)|
| Filters enabled in Adguard:| (e.g. English, Annoyances)|
| Device model:| (e.g. Google Pixel)|
| Operating system and version:| (e.g. Android 7.1.2)|
| Rooted or not? | (Yes/No) |

**Comment by Chinaski1** [comment]
@psgomez 

The easiest way to get an AdGuard content blocker is to open the [Google Playstore](https://play.google.com/store/apps/details?id=com.adguard.android.contentblocker&hl=en&gl=US) and install it directly from the PS.
Then open your browser (Samsung or Yandex) -> [Settings](https://uploads.adguard.com/Chinaski9hzmx.png) -> [Add-ons](https://uploads.adguard.com/Chinaski0cnj1.png) -> AdBlockers -> [Enable AdGuard content blocker.](https://uploads.adguard.com/Chinaski1mojp.png)

Let us know the result ;)

**Comment by psgomez** [comment]
Well waited,then,deleted it and searched for another suppliers product..
