### ISSUE TITLE
Android 

### ISSUE THREAD

**Issue by tunsira** [AdguardTeam/ContentBlocker#274]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Browser:**
  - 
- **Device model:**
  - 
- **Operating system and version:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Chinaski1** [comment]
Hello!

The issue turned out to be an empty one :)
Please clarify your question.
