### ISSUE TITLE
Training outdoor

### ISSUE THREAD

**Issue by issamahmoud355** [AdguardTeam/ContentBlocker#278]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Additional Information

MHM1lik

**Comment by Chinaski1** [comment]
Additional information is also needed, both in #276
