### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by Andyadame** [AdguardTeam/ContentBlocker#285]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Additional Information

Mensajes

**Comment by Andyadame** [comment]
Que puedo hacer

**Comment by Andyadame** [comment]
lastpass@logmein.com
También quiero descansar esta aplicación

**Comment by Chinaski1** [comment]
Please ask a more precise question and describe your issue in more detail via email to support@adguard.com
