### ISSUE TITLE
Ynadex.browser "freezed" after it was installed from ContentBlocker onboarding

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/ContentBlocker#30]
изначальные условия:
адгарда нет, я.браузера нет

1. ставим контент блокер
2. из онбординга идем и ставим я.браузер
3. нас возвращает после установки браузера в онбординг (наш)
4. переходим на 3 шаг онбординга
5. идем включать контент блокер
6. двыжды жмем кнопу “назад” (выходим из браузера)

В результате висит окно я.браузера: <img src="https://files.slack.com/files-pri/T0B41S97U-F27PM5Z0F/screenshot_20160902-182919.png" width="300">

**Comment by ameshkov** [comment]
Done
