### ISSUE TITLE
Content Blocker v2.7.0 crashing with Samsung Internet Beta v18.0.0.32

### ISSUE THREAD

**Issue by myculito** [AdguardTeam/ContentBlocker#303]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  2.7.0
- **Browser:**
  Samsung Internet Browser Beta v18.0.0.32
- **Device model:**
  Samsung Galaxy S22 Ultra Unlocked
- **Operating system and version:**
 Android v12, June 1 security update

### Expected Behavior

Ads are blocked on any website

### Actual Behavior

Adguard 2.7.0 makes the Samsung Internet Browser Beta to crash. Uninstalling Adguard resolves the site crashes. Once you reinstall Adguard and it updates to 2.7.0, the browser starts to crash again.

### Screenshots
![Screenshot_20220630-120735_AdGuard Content Blocker](https://user-images.githubusercontent.com/40244651/176725918-a0342c57-a541-4c76-97d3-fc73f8fae148.jpg)
![Screenshot_20220630-120749_Samsung Internet Beta](https://user-images.githubusercontent.com/40244651/176725920-ebe17deb-b3e2-4364-bf79-eb8daf80e7f6.jpg)

**Comment by ameshkov** [comment]
Could you please report it to Samsung? The bug is on their side.
