### ISSUE TITLE
Discontinue Content Blocker due to zero maintenance, and move people over to AdGuard's Firefox Android version

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/ContentBlocker#315]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - We can assume v2.6.2 for this, based on https://github.com/AdguardTeam/ContentBlocker/releases
- **Browser:**
  - N/A
- **Device model:**
  - N/A
- **Operating system and version:**
  - We can assume Android 10 for this.

### Expected Behavior

List selections and list entries are reasonably up to date.

### Actual Behavior

It was brought to my attention this morning that [the lists included in Content Blocker are very, very, very outdated](https://github.com/AdguardTeam/ContentBlocker/tree/master/adguard_cb/src/main/res/raw), with neither the list selection nor list entries having been updated since November 2019(!).

So unless enormous improvements and very critical maintenance are done to the linked-to-above Git folder within the next 2 weeks, it's time to declare Content Blocker to be a thing of the past, and to tell all users of Content Blocker to transition to *AdGuard for Firefox for Android* instead, and to actually do marketing and promotions for that particular AdGuard version.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/209530395-257051d7-db1b-439f-a7d5-8d67c53a8d74.png)

</details>

### Additional Information

None that I'm currently aware of.

**Comment by ameshkov** [comment]
We actually have big plans on this version of AdGuard, just don't have resources to address it quickly. Hopefully, next year you'll finally see the development here.

**Comment by leonborin** [comment]
Hi, this content blocker edition still not yet updated at all as of August 2023, are adguard team deprecated this version?
