### ISSUE TITLE
Dark theme feature request

### ISSUE THREAD

**Issue by vedavyawhss** [AdguardTeam/ContentBlocker#316]
### Steps to reproduce

1. Add Dark theme option.

### Expected behavior

Dark theme required for AdGuard Content Blocker app (because it's 2023)

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| (e.g. 1.6.10)|
| Browser in use:| (Samsung Interner/Yandex Browser)|
| Filters enabled in Adguard:| (e.g. English, Annoyances)|
| Device model:| (e.g. Google Pixel)|
| Operating system and version:| (e.g. Android 7.1.2)|
| Rooted or not? | (Yes/No✓) |

**Comment by SHORTYMACK** [comment]
Haha rooted or not
