### ISSUE TITLE
There seems to be an issue after updating my ipad to the latest software version ipados15.7.6 the issues I've encountered are the constant connection resets and as a concequence when the adguard protection on for youtube the setting is no longer valid and has to be enabled again, but quite too often it remains active only for one or two videos and doesn't work as it used to. The same goes for my iphone 7 running on the latest software, ios 15.7.6  but the same issues are persisting. Being otherwise a relatively satisfied user of adguard I find it strange that the support team is not addressing these issues rendering it ineffective.

### ISSUE THREAD

**Issue by Thomas197906** [AdguardTeam/ContentBlocker#326]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Browser:**
  - 
- **Device model:**
  - 
- **Operating system and version:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by krystian3w** [comment]
You should shorter title and move more informations to sections:

- Issue Details
- Expected Behavior
- Actual Behavior
