### ISSUE TITLE
Missed separator between blocks on main window.

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/ContentBlocker#33]
_How it looks on Samsung:_
<img src="https://cloud.githubusercontent.com/assets/8577547/18556916/966d51f4-7b75-11e6-9b70-36c47ca0b564.jpg" width="250">

_How it should look like:_
<img src="https://cloud.githubusercontent.com/assets/8577547/18556895/83f6212c-7b75-11e6-87f3-3308a5c421ab.png" width="250">

**Comment by nkartyshov** [comment]
fixed
