### ISSUE TITLE
Add new localizations

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ContentBlocker#45]
New languages:
Ukranian, Chinese Simplified, Japanese, Spanish (Latin America), Hungarian, Dutch, Italian.

They are ready in OneSkyApp.

**Comment by ameshkov** [comment]
And turkish

**Comment by nkartyshov** [comment]
Added languages: Dutch, Italian, Hungarian, Croatian and Turkish

**Comment by nkartyshov** [comment]
Added languages: Italian and Chinese Simplified

**Comment by nkartyshov** [comment]
Added languages: Ukranian, Spanish (Latin America)

**Comment by nkartyshov** [comment]
Done, added all languages.
