### ISSUE TITLE
Switch to new filters servers

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#46]
Just like it's described here:
https://github.com/AdguardTeam/AdguardForAndroid/issues/863

@atropnikov 
Also we should add one more platform:
`extension/android-content-blocker/`

Limit it to rules with basic ABP syntax.
No extended CSS, no advanced rules ($replace, $mp4 and such), no CSS, no JS, no HTML filtering

**Comment by nkartyshov** [comment]
done
