### ISSUE TITLE
Wrongly Blocking Non-ad Elements

### ISSUE THREAD

**Issue by melaus** [AdguardTeam/ContentBlocker#47]
An example is cosstores.com . When clicking on a product to see more information about it, it just does nothing. This is happening when using Samsung Internet with Adguard for Android.

**Comment by melaus** [comment]
I forgot to mention - this is happening when using Samsung Internet with Adguard for Android.

**Comment by ameshkov** [comment]
Hi, and thank you for reporting it!

Actually, the problems with ad blocking should be reported to the https://github.com/AdguardTeam/AdguardFilters repo.

I've moved this issue there already:
https://github.com/AdguardTeam/AdguardFilters/issues/3980
