### ISSUE TITLE
epidemz.com,epidemz.co - Can't hide banner

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ContentBlocker#51]
<details>

![image](https://cloud.githubusercontent.com/assets/25342327/22749822/50ead8ec-ee37-11e6-81f1-d0cedb56bc77.png)

</details>

This banner should be blocked by these rules(1st - in the Russian filter, 2nd - in mobile)
`epidemz.co,epidemz.com##.topreklama`
`epidemz.com,epidemz.co##div[id^="cpa_rotator_block_"]`
Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/4307

**Comment by nkartyshov** [comment]
@Alex-302 Problem with first rules.
Correct rules: `epidemz.com,epidemz.co##.topreklama`

**Comment by Alex-302** [comment]
@nkartyshov But why? Domains are the same, selectors are equal.

**Comment by nkartyshov** [comment]
Yes, but I didn't find information about it. Maybe, It is bug in Content Blocker for browser.
