### ISSUE TITLE
Failed to block some advertising

### ISSUE THREAD

**Issue by 3pelin** [AdguardTeam/ContentBlocker#55]
The advertising blocker blocks the content but does not suppress the frame that accompanies the advertisement.

I have activated all the filters but this does not solve the problem either.
![screenshot_20170302-205935](https://cloud.githubusercontent.com/assets/22451687/23535475/8aa29690-ff8c-11e6-928f-f65735c87175.png)

**Comment by 3pelin** [comment]
![screenshot_20170302-205935](https://cloud.githubusercontent.com/assets/22451687/23535429/49834cae-ff8c-11e6-8b47-b67192ac499c.png)
![screenshot_20170302-205935](https://cloud.githubusercontent.com/assets/22451687/23535435/5750f1ce-ff8c-11e6-8fa8-e8e30517f0b3.png)

**Comment by Alex-302** [comment]
please write to Filters repository
https://github.com/AdguardTeam/AdguardFilters/issues
