### ISSUE TITLE
Samsung browser is now available on non-samsung devices

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#56]
So we should allow people to choose & install it.

**Comment by Alex-302** [comment]
Google Play says it is not supported on my device(Sony Xperia Z1c), but Samsung browser is available in AG

![image](http://imagizer.imageshack.com/img924/2966/OOa4qM.png)

**Comment by ameshkov** [comment]
Beta version is available:
https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser.beta

**Comment by ameshkov** [comment]
Ah, sorry, it seems that i am wrong

**Comment by seanl-adg** [comment]
It is not currently available in all country. It is not available in US.

**Comment by seanl-adg** [comment]
Now the app is available in other countries too.
The apk can be downloaded at: http://www.apkmirror.com/apk/samsung-electronics-co-ltd/samsung-internet-beta/samsung-internet-beta-5-4-00-3-release/samsung-internet-beta-5-4-00-3-android-apk-download/

**Comment by nkartyshov** [comment]
Fixed

**Comment by seanl-adg** [comment]
Now, it only shows Samsung browser beta and does not show Samsung browser in the main page. So I can't access settings page of Samsung browser from the Adguard main screen.
Their package names are different: `com.sec.android.app.sbrowser` and `com.sec.android.app.sbrowser.beta`

**Comment by ameshkov** [comment]
> Now, it only shows Samsung browser beta and does not show Samsung browser in the main page. 

As I recall, we have one block for Samsung, it will correspond to either beta or release browser (beta has higher priority).

**Comment by seanl-adg** [comment]
So is it not an issue? Users may have both browser installed in the device and cannot access the configuration page directly from Adguard app.

**Comment by ameshkov** [comment]
> So is it not an issue?

It might be an issue, but it's not a bug. File a change request plz.
