### ISSUE TITLE
Add a third-party filter List-KR to available filters

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/ContentBlocker#57]
As in other platforms, add List-KR filter to available filters and make it default for Korean users.

**Comment by nkartyshov** [comment]
Added

**Comment by seanl-adg** [comment]
There will be some unhandled problems if List-KR is used without Safari filter - indeed the same is true for English filter, for example, we put rules alternative to CSS or JS rules to Safari filter.

We can make Safari filter available and make it default for all users. Or in this specific filter, if it is possible to exclude several rules in the filter for the content blocker platform only, it will be okay.

**Comment by nkartyshov** [comment]
@seanl-adg  We aren't use Safari Filter in Android. He uses in iOS and OS X.

**Comment by seanl-adg** [comment]
Why don't make the Safari filter available in Android too?
It won't be needed in AG for Android, but will still be useful in content blockers.

**Comment by Alex-302** [comment]
It will be better, if Safari filter will be renamed to something related to content blockers.

**Comment by ameshkov** [comment]
Agreed with @Alex-302 . In any case, we can add it to content blocker as is right now.

**Comment by nkartyshov** [comment]
Added Safari Filter.

**Comment by seanl-adg** [comment]
On my device Safari filter was not enabled, and updating the app didn't enable Safari filter automatically.
Because of its naming, users are likely not to enable it, so we somehow need to enable it in upcoming updates.

**Comment by ameshkov** [comment]
Filed a new issue:
https://github.com/AdguardTeam/ContentBlocker/issues/65
