### ISSUE TITLE
Add screenshots to adguard.oneskyapp.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#59]
It would be much easier to  translate content blocker.

**Comment by nkartyshov** [comment]
Added

**Comment by seanl-adg** [comment]
Could you add screenshots for the following phrases?
```
#22858445 
#21728385 
#28498010 
```

**Comment by nkartyshov** [comment]
@seanl-adg Thank you! I added screenshot for phasers 22858445 and 21728385, but we don't use phaser 28498010. We will delete phaser 28498010 in next update.

**Comment by seanl-adg** [comment]
Hi, I'm still not seeing a screenshot for #21728385, could you check again please?

**Comment by nkartyshov** [comment]
@seanl-adg Sorry, I mistaken for the phasers. We don't use phaser #21728385 and we will delete that in next update. And I added screenshot for phaser #28498010.
