### ISSUE TITLE
A few Pop up ads 

### ISSUE THREAD

**Issue by cabban** [AdguardTeam/ContentBlocker#61]
Www.dreamfilmhd.bz
Www.swefilm.tv
Www.dreamfilm.se
Www.dreamfilmhd.sh

Hope u could fix this
Adguard
Rocks
You are great:-)

**Comment by Alex-302** [comment]
It is impossible to block popups on these tites without JS or $empty modifier.
Try:
```
||pop.redirect.adsjudo.com^
```
