### ISSUE TITLE
Publish to F-Droid

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#62]
https://github.com/AdguardTeam/AdguardForAndroid/issues/1148

https://f-droid.org/
https://f-droid.org/en/docs/Inclusion_Policy/
https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by duongvanbo789** [comment]
#94

**Comment by ameshkov** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/2890

**Comment by ameshkov** [comment]
@nkartyshov there're some new comments that need to be addressed:
https://gitlab.com/fdroid/fdroiddata/merge_requests/2890

**Comment by vbagirov** [comment]
Weren't they addressed already? The last update there seem to be @nkartyshov's commit.

**Comment by nkartyshov** [comment]
I commented on the pull request and mentioned the member the f-droid in it

**Comment by superlex** [comment]
ContentBlocker is now available on F-Droid :)
https://f-droid.org/en/packages/com.adguard.android.contentblocker/

However it is not recognized by Samsung Internet Browser, so it doesn't work.
Could you check?
Thanks :)

**Comment by ameshkov** [comment]
🎉 :)

**Comment by ameshkov** [comment]
> However it is not recognized by Samsung Internet Browser, so it doesn't work.

Waiting for an answer from Samsung now.

**Comment by superlex** [comment]
It's recognized by Yandex but still not Samsung (v. 9.2.00.70) :(

**Comment by superlex** [comment]
PS:
@ameshkov 
Uhm.. It appears " superlex unassigned nkartyshov " but I didn't O.o

**Comment by ameshkov** [comment]
> It's recognized by Yandex but still not Samsung (v. 9.2.00.70) :(

Yeah, and Samsung ignores our emails so I am not sure if this can be fixed:(

**Comment by licaon-kter** [comment]
@ameshkov Thoughts? https://f-droid.org/wiki/page/com.adguard.android.contentblocker/lastbuild_22000006

**Comment by artemiv4nov** [comment]
@licaon-kter We'll publish the last build to F-Droid soon.
