### ISSUE TITLE
Filters are not being updated for the app version from Galaxy Store

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#67]
@nkartyshov we should solve this issue ASAP and upload the updated version to both Galaxy Store and Google Play.

I suggest we first update the embedded filters and upload it and then investigate the auto-update issue.

**Comment by ameshkov** [comment]
@nkartyshov when do we check filters updates after the first installation?

**Comment by nkartyshov** [comment]
@ameshkov We checks filter update after 1 hour after first installed.

**Comment by ameshkov** [comment]
We'd better change the initial period to 5 mins.
