### ISSUE TITLE
wrong blocking

### ISSUE THREAD

**Issue by monastyrski** [AdguardTeam/ContentBlocker#73]
Adblock - Persian list enabled in Adguard for Android blocks in Samsung Internet browser the "search" button both on English ( http://www.israelpost.co.il/itemtrace.nsf/mainsearchNOHE?OpenForm&L=EN ) and on Hebrew ( http://www.israelpost.co.il/itemtrace.nsf/mainsearch?openform ) item tracking pages of Israel Post website.

**Comment by vozersky** [comment]
Hi!
Filtering issues are reported here:  https://github.com/AdguardTeam/AdguardFilters

**Comment by vozersky** [comment]
@evgeniy-ADG please move it
