### ISSUE TITLE
Add Yandex.Browser.Light to Adguard Content Blocker

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/ContentBlocker#74]
Feature request: to add Yandex.Browser.Light to the list of browsers that are filtered by Adguard Content Blocker.

**Comment by ameshkov** [comment]
That's not we who makes the decision. Yandex browser light does not support content blockers.

**Comment by ameshkov** [comment]
I guess the proper place to create a feature request like that is Yandex, maybe one day they will add content blockers support.

**Comment by kbahlyk** [comment]
Forwarded the answer to the customer.
