### ISSUE TITLE
www.carrollcountytimes.com

### ISSUE THREAD

**Issue by sshayss** [AdguardTeam/ContentBlocker#75]
I had you fix issues with this website for the adguard.apk app that works by using a vpn.  Now I hope you can fix it for the Samsung Browser Content Blocker extension.

**Comment by vozersky** [comment]
Hi! [This](https://github.com/AdguardTeam/AdguardFilters/issues/5137) was your report, right? Please refer to the same issue for discussion. It might not be possible to do the same for Adguard content blocker though, browser's content blocking API has A LOT of restrictions

**Comment by sshayss** [comment]
Yes.  That was me.  I don't get the popup, I just get ads while scrolling (see attached).  The reason I switched was due to persistent Android notification about VPN.
-------- Original message --------From: Vladimir Ozersky <notifications@github.com> Date: 7/12/17  6:42 AM  (GMT-05:00) To: AdguardTeam/ContentBlocker <ContentBlocker@noreply.github.com> Cc: sshayss <scottsamuelhays@gmail.com>, Author <author@noreply.github.com> Subject: Re: [AdguardTeam/ContentBlocker] www.carrollcountytimes.com (#75) 
Hi! This was your report, right? Please refer to the same issue for discussion. It might not be possible to do the same for Adguard content blocker though, browser's content blocking API has A LOT of restrictions

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AdguardTeam/ContentBlocker","title":"AdguardTeam/ContentBlocker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AdguardTeam/ContentBlocker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vozersky in #75: Hi! [This](https://github.com/AdguardTeam/AdguardFilters/issues/5137) was your report, right? Please refer to the same issue for discussion. It might not be possible to do the same for Adguard content blocker though, browser's content blocking API has A LOT of restrictions"}],"action":{"name":"View Issue","url":"https://github.com/AdguardTeam/ContentBlocker/issues/75#issuecomment-314724739"}}}
