### ISSUE TITLE
Feedback/Contact Us option 

### ISSUE THREAD

**Issue by nfilz** [AdguardTeam/ContentBlocker#76]
I realize this is more of a feature request than a bug, but some sort of contact us or feedback option in the app would be heloful. 

I.e. I'm a developer so I wouldn't do this, but the app was causing some frustrations with the latest version of Android Or and Samsung browser. A normal person probably would have just left bad feedback in the play store/Samsung store. If they couldn't find a contact/questions page.

**Comment by ameshkov** [comment]
@nfilz thank you!

@seanl-adg , let's add two more items to the navigation drawer.

1. "Report a bug" should lead to https://github.com/AdguardTeam/ContentBlocker/issues/new
2. "Github" should lead to https://github.com/AdguardTeam/ContentBlocker

Icons:
[icons.zip](https://github.com/AdguardTeam/ContentBlocker/files/1144712/icons.zip)
