### ISSUE TITLE
Change Samsung browser detection logic

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#8]
> 2.  If you want to check whether the Content Blocker feature is available or not with current device, you can use below logic.
>       ( starting from 4.0, Samsung Internet for Android supports Content Blocker)

```
               Intent intent = new Intent();
               intent.setAction("com.samsung.android.sbrowser.contentBlocker.ACTION_SETTING");
               List<ResolveInfo> list = getPackageManager().queryIntentActivities(intent, 0);
               if(list.size() > 0) {    
                   // Samsung Internet 4.0 was installed. 
               }
```

>        If the user didn't install Samsung Internet 4.0 for content blocker, you can guide the user to do so by providing an option to access to Play Store Link. 
>        - Samsung Internet in Google Play : https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser

**Comment by Revertron** [comment]
I am doing it like this exactly.

**Comment by ameshkov** [comment]
Ah, ok, nice.
