### ISSUE TITLE
Add information about other AG products/platforms

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#82]
Here's the mockup:
https://uploads.adguard.com/up04_zs6mk_Adguard_for_Android_-_AdGuard_Content_Blocker__Moqups_.png

Basically, this is a pattern from the material guidelines:
https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B7WCemMG6e0VNU9vaEV1dWxaMlE/patterns-usereducation-06-offer.png

1. We should show this notification when AdGuard CB is enabled in any of the browsers.
2. After the user clicks "No thanks" or "Learn more", we should not show it anymore.
3. "Learn more" link leads to this: http://agrd.io/cb_adguard_products

**Comment by nkartyshov** [comment]
done
