### ISSUE TITLE
Update "README", CONTRIBUTING, add information about translations, etc

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#83]

**Comment by vbagirov** [comment]
@ameshkov https://github.com/AdguardTeam/ContentBlocker/pull/101 - done.

**Comment by ameshkov** [comment]
@vbagirov please add beta test link to README

**Comment by vbagirov** [comment]
@ameshkov https://github.com/AdguardTeam/ContentBlocker/pull/102

**Comment by vbagirov** [comment]
Done, closing.
