### ISSUE TITLE
Report bug

### ISSUE THREAD

**Issue by minhky** [AdguardTeam/ContentBlocker#84]
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| (e.g. 1.6.10)|
| Browser in use:| (Samsung Interner/Yandex Browser)|
| Filters enabled in Adguard:| (e.g. English, Annoyances)|
| Device model:| (e.g. Google Pixel)|
| Operating system and version:| (e.g. Android 7.1.2)|
| Rooted or not? | (Yes/No) |

**Comment by zebrum** [comment]
@minhky hi there! Do you want to report something?

**Comment by vozersky** [comment]
@minhky hi, please provide more details if you experience any issues
