### ISSUE TITLE
$document modifier does not work in Yandex browser

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ContentBlocker#85]
http://4pda.ru/forum/index.php?showtopic=771100&view=findpost&p=64862086
For example:
http://server.cheb.ru/
the rule
`@@||server.cheb.ru^$document`
Yandex Browser alpha 17.9
It works in Samsung Internet beta.

**Comment by ameshkov** [comment]
Reported to Yandex browser devs

**Comment by ameshkov** [comment]
Resolved
