### ISSUE TITLE
The content blocker doesn't work on Oreo Beta

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ContentBlocker#95]
> I'm using a OnePlus 5T running Oreo Beta and the Adblock doesn't work. I'm using Samsung browser.

### Actual behavior

<details><summary>Screenshot 1:</summary>

* ![image](https://user-images.githubusercontent.com/15856304/34765647-bafd5b12-f5fa-11e7-839d-ed4306371e08.png)

</details>

<details><summary>Screenshot 2:</summary>

![image](https://user-images.githubusercontent.com/15856304/34765659-bf823f68-f5fa-11e7-97da-3a960ea82076.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| the current release version
| Browser in use:| (Samsung Interner/Yandex Browser)| Samsung
| Filters enabled in Adguard:| (e.g. English, Annoyances)| n/a
| Device model:| (e.g. Google Pixel)| OnePlus 5T
| Operating system and version:| (e.g. Android 7.1.2)| Oreo Beta
| Rooted or not? | (Yes/No) | n/a

**Comment by scaredyet** [comment]
So what's the latest? It's still not working. It doesn't update automatically. I'm using a OnePlus 5T with Android Oreo Beta.

I manually enable the content blocker but then when it doesn't update it just says not working.

**Comment by nkartyshov** [comment]
@scaredyet  What versions of the Samsung browser and content blocker are you using?

**Comment by scaredyet** [comment]
![screenshot_20180115-213010](https://user-images.githubusercontent.com/35383624/34938208-4fdaaec8-f9df-11e7-955d-54d9108b2939.jpg)
![screenshot_20180115-213025](https://user-images.githubusercontent.com/35383624/34938212-54b8c0ba-f9df-11e7-9343-67f3babdde52.jpg)

**Comment by nkartyshov** [comment]
@scaredyet  Can you update the Samsung browser to 6.4.00.6(latest stable version)?
If the problem persists, can you record the logсat? 
How to do it, see here: [How to Capture a Logcat for Detailed Bug Reports](https://android.gadgethacks.com/how-to/android-basics-capture-logcat-for-detailed-bug-reports-0167774/)
